### ISSUE TITLE
panic when n = 5 and m = 33

### ISSUE THREAD

**Issue by choleraehyq** [ksang/maghash#1]
use this patch:
```
diff --git a/maglev_test.go b/maglev_test.go
index 4feb9dd..6befd9e 100644
--- a/maglev_test.go
+++ b/maglev_test.go
@@ -64,14 +64,14 @@ func printLookup(entry []int) {

 func TestPermutation(t *testing.T) {
        magh := magHash{
-               m:        int32(17),
+               m:        int32(33),
                backends: make([][]byte, 0),
                bIndex:   make(map[string]int),
-               entry:    make([]int, 17),
+               entry:    make([]int, 33),
        }
-       bes := make([]string, 10)
-       for i := 0; i < 10; i++ {
-               bes[i] = strconv.FormatInt(rand.Int63(), 10)
+       bes := make([]string, 5)
+       for i := 0; i < 5; i++ {
+               bes[i] = strconv.FormatInt(rand.Int63(), 5)
        }
        if err := magh.AddBackends(bes); err != nil {
                t.Error(err)
```
```
panic: runtime error: index out of range

goroutine 21 [running]:
github.com/ksang/maghash.(*magHash).populate(0xc00008e2c0)
	/Users/cholerae/Documents/gopath/src/github.com/ksang/maghash/maglev.go:119 +0x1c8
github.com/ksang/maghash.(*magHash).AddBackends.func1(0xc00008e2c0)
	/Users/cholerae/Documents/gopath/src/github.com/ksang/maghash/maglev.go:148 +0x42
created by github.com/ksang/maghash.(*magHash).AddBackends
	/Users/cholerae/Documents/gopath/src/github.com/ksang/maghash/maglev.go:146 +0x136
exit status 2
FAIL	github.com/ksang/maghash	0.009s
```

**Comment by ksang** [comment]
Thanks, M must be a prime number, I'll add check.

**Comment by ksang** [comment]
The exported interface already has prime number check, so won't add addtional check in internal packet to aviod extra overhead. Added some doc for clarification.
857ed74e24b6c6d8953eb22823fe3bd24c92cf39
